#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# MatClaw native installer
# Works on macOS and Linux. Windows users: use WSL or Docker.
#
# Usage:
#   chmod +x install.sh && ./install.sh
#
# What it does:
#   1. Checks Python 3.11+ and Node 18+ are available
#   2. Creates a .venv and installs Python deps
#   3. Builds the React frontend
#   4. Copies .env.example → .env (if not already present)
#   5. Creates a `matclaw` launcher script at /usr/local/bin/matclaw
#      (or ~/bin/matclaw if /usr/local/bin is not writable)
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail

BOLD=$(tput bold 2>/dev/null || echo "")
RESET=$(tput sgr0 2>/dev/null || echo "")
GREEN="\033[32m"
YELLOW="\033[33m"
RED="\033[31m"
NC="\033[0m"

info()    { echo -e "${GREEN}▶${NC}  $*"; }
warn()    { echo -e "${YELLOW}⚠${NC}  $*"; }
error()   { echo -e "${RED}✗${NC}  $*" >&2; exit 1; }
success() { echo -e "${GREEN}✓${NC}  ${BOLD}$*${RESET}"; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

echo ""
echo -e "${BOLD}MatClaw Installer${RESET}"
echo "─────────────────────────────────────────────"

# ── 1. Python ─────────────────────────────────────────────────────────────────
info "Checking Python version..."
PYTHON=""
for cmd in python3.11 python3 python; do
    if command -v "$cmd" &>/dev/null; then
        version=$("$cmd" -c "import sys; print(sys.version_info[:2])")
        if "$cmd" -c "import sys; sys.exit(0 if sys.version_info >= (3,11) else 1)" 2>/dev/null; then
            PYTHON="$cmd"
            break
        fi
    fi
done
[ -z "$PYTHON" ] && error "Python 3.11+ is required. Install from https://python.org/downloads"
success "Found Python: $($PYTHON --version)"

# ── 2. Node ───────────────────────────────────────────────────────────────────
info "Checking Node.js..."
if ! command -v node &>/dev/null; then
    warn "Node.js not found. Skipping frontend build (use pre-built dist if available)."
    BUILD_FRONTEND=false
else
    NODE_MAJOR=$(node -e "console.log(process.versions.node.split('.')[0])")
    if [ "$NODE_MAJOR" -lt 18 ]; then
        warn "Node.js 18+ recommended (found $NODE_MAJOR). Frontend build may fail."
    fi
    success "Found Node.js: $(node --version)"
    BUILD_FRONTEND=true
fi

# ── 3. Virtual environment ────────────────────────────────────────────────────
info "Setting up Python virtual environment..."
if [ ! -d ".venv" ]; then
    "$PYTHON" -m venv .venv
    success "Created .venv"
else
    success "Reusing existing .venv"
fi

source .venv/bin/activate
pip install --upgrade pip --quiet

info "Installing Python dependencies..."
pip install --quiet -e ".[dev]"
success "Python dependencies installed"

# ── 4. Build frontend ─────────────────────────────────────────────────────────
if [ "$BUILD_FRONTEND" = true ]; then
    info "Building React frontend..."
    cd web
    npm ci --silent
    npm run build --silent
    cd ..
    success "Frontend built → web/dist/"
else
    if [ -d "web/dist" ]; then
        success "Using existing frontend build at web/dist/"
    else
        warn "No frontend build found. The UI will not work until you run: cd web && npm run build"
    fi
fi

# ── 5. Environment file ───────────────────────────────────────────────────────
if [ ! -f ".env" ]; then
    cp .env.example .env
    warn ".env created from .env.example — open it and add your API key before starting."
else
    success ".env already exists"
fi

# ── 6. Create launcher ────────────────────────────────────────────────────────
LAUNCHER_CONTENT="#!/usr/bin/env bash
# MatClaw launcher — generated by install.sh
cd \"$SCRIPT_DIR\"
source .venv/bin/activate
exec python -m src.matclaw.api.main \"\$@\"
"

INSTALL_BIN=""
if [ -w "/usr/local/bin" ]; then
    INSTALL_BIN="/usr/local/bin/matclaw"
elif [ -d "$HOME/bin" ]; then
    INSTALL_BIN="$HOME/bin/matclaw"
elif [ -d "$HOME/.local/bin" ]; then
    INSTALL_BIN="$HOME/.local/bin/matclaw"
fi

if [ -n "$INSTALL_BIN" ]; then
    echo "$LAUNCHER_CONTENT" > "$INSTALL_BIN"
    chmod +x "$INSTALL_BIN"
    success "Launcher installed: matclaw"
else
    warn "Could not install to PATH. Run manually with: ./start.sh"
fi

# Always create ./start.sh as a fallback
echo "$LAUNCHER_CONTENT" > start.sh
chmod +x start.sh
success "Created ./start.sh"

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
echo -e "${BOLD}─────────────────────────────────────────────${RESET}"
success "MatClaw installed successfully!"
echo ""
echo "  Next steps:"
echo "  1. Edit .env and add your LLM API key"
echo "  2. Run:  matclaw        (or ./start.sh)"
echo "  3. Open: http://localhost:8000"
echo ""
echo "  For full MATLAB integration:"
echo "  • Set MATCLAW_MATLAB__ENABLED=true in .env"
echo "  • Ensure MATLAB is running before starting MatClaw"
echo ""
