#!/usr/bin/env bash
# MatClaw launcher — generated by install.sh
# Fresh wipe (memory, sessions, plots, Chroma): python scripts/reset_local_state.py --kill-server
cd "/Users/abishek/MatClaw"
source .venv/bin/activate
exec python -m matclaw.api.main "$@"

